### ISSUE TITLE
scons fails to install on CentOS7

### ISSUE THREAD

**Issue by Leo675** [kallisti5/ElectricFence#1]
Hello, I have a quick fix for the scons install process. 

Steps to reproduce issue:
cd src
scons

> no SConstruct file found

rename to SConstruct

> error on Import("env")

I'm new to scons but I had to rename the install script to SConstruct (maybe there's a way to manually specify the file name, but it didn't work for me)

Also I had to add two lines to SConstruct to make Import("env") work:

> env = Environment()
> Export('env')

scons installed via yum:
scons -v
SCons by Steven Knight et al.:
        script: v2.3.0, 2013/03/03 09:48:35, by garyo on reepicheep
        engine: v2.3.0, 2013/03/03 09:48:35, by garyo on reepicheep
        engine path: ['/usr/lib/scons/SCons']

**Comment by kallisti5** [comment]
You're only supposed to build from the top level with scons. Don't cd to src.
